name: Build and Test C# Application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    env:
      ConnectionStrings__DefaultConnection: ${{ secrets.DATABASE_CONNECTION_STRING }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x' # Adjust to your .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build --no-restore

      - name: Run application
        run: dotnet run --project DatabaseConnectionApp/DatabaseConnectionApp.csproj
